parameters:
    jihel.vikingpay.form.credit_card.class: Jihel\VikingPayBundle\Form\CreditCardType

services:
    jihel.vikingpay.form.credit_card:
        class: %jihel.vikingpay.form.credit_card.class%
        tags:
            - { name: form.type, alias: jihel_viking_pay_credit_card }
            - { name: payment.method_form_type }
